version: "3.9"

services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    networks:
      jenkins_network:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ./mnt/jenkins_data:/var/jenkins_home
      - ./mnt/jenkins_certs:/certs/client
    ports:
      - "2376:2376"
  jenkins:
    build:
      context: ./jenkins
    networks:
      - jenkins_network
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./mnt/jenkins_data:/var/jenkins_home
      - ./mnt/jenkins_certs:/certs/client

networks:
  jenkins_network:
